---
title: "explore_data"
author: "Charles Hendrickson"
date: "2023-06-08"
output: html_document
---

Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(naniar)
library(janitor)
library(here)
library(readxl)
library(naniar)
options(scipen = 99)
```

Load Data
```{r}
census_data <- read_excel(here("data/census_data.xls"))
```
Tidy Data
```{r}
#Delete rows before the third row
census_data <- census_data %>% row_to_names(row_number = 4)

#Rename column
census_data <- census_data %>% 
       rename("household_language" = "Detailed household language")

#Pivot longer
census_data <- census_data %>%
  pivot_longer(-household_language, names_to = "state", values_to = "speakers")

#Filter data
census_data <- filter(census_data, household_language != "-> Total")

```

Filter rows and remove missing values
```{r}
#Remove all rows for total number of speakers for all states
census_data <- filter(census_data, state != "Total")

#Remove missing values
census_data <- filter(census_data, household_language != "N/A (GQ/vacant)")
```


```{r}
#Make data type numeric
census_data$speakers <- as.numeric(census_data$speakers)

#Calculate the number of speakers for each language
census_data <- census_data %>% group_by(household_language) %>% mutate(total_speakers_by_language = sum(speakers))

#Find the percent of speakers for each state
census_data <- census_data %>% mutate(percent_speakers = speakers/total_speakers_by_language*100)
```


```{r}
#Total number of speakers in the state
census_data <- census_data %>% group_by(state) %>% mutate(total_speakers_by_state = sum(speakers))

#Percent of state that speaks the language
census_data <- census_data %>%
  mutate(percent_speakers_by_state = speakers/total_speakers_by_state*100)

```

Round to two decimal places
```{r}
#Round percentages to two decimal places
census_data <- census_data %>% mutate(across(where(is.numeric), ~ round(., digits = 2)))
```

Export the dataframe to CSV
```{r}
write.csv(census_data,
          "final_census_data.csv", row.names=FALSE)
```






