---
title: "updated_data_exploration"
author: "Charles Hendrickson"
date: "2023-07-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(naniar)
library(visdat)
library(janitor)

#Turn off scientific notation as global setting
options(scipen=999)
```

Read in data
```{r}
lang_app_data <- read_csv(here("data/LangAppData.csv"))
```

Explore missing data
```{r}
vis_dat(lang_app_data)
```

Clean and prepare data
```{r}
#made column names lowercase
lang_app_data <- clean_names(lang_app_data)

#rename columns 
lang_app_data <- lang_app_data %>%
         rename("household_language" = "lanp_label",
                "state" = "st_label",
                "speak_english" = "eng_label",
                "speakers" = "n")

#create new column for state abbreviations
lang_app_data <- lang_app_data %>% separate(col = state, into = c("state", "state_abb"), sep = "/")

#check data type of columns
summary(lang_app_data)

#Remove 'state_abb' column becuase it is unnecessary
```

Get stats on languages and make new columns
```{r}
#Create new column of the total number of speakers of each language
lang_app_data <- lang_app_data %>% 
                 group_by(household_language) %>% 
                 mutate(total_speakers_of_language_in_us = sum(speakers))

#Find the percent of speakers for each state
lang_app_data <- lang_app_data %>% mutate(percentage_speakers_in_state = speakers/total_speakers_of_language_in_us*100)

#Find the population of individuals with household language that is not English 
lang_app_data <- lang_app_data %>% group_by(state) %>% mutate(state_pop_of_non_english_households = sum(speakers))

#Find Percent of State Pop. Speaking Language
lang_app_data <- lang_app_data %>% mutate(percent_state_pop_speaking_language = speakers/state_pop_of_non_english_households*100)
```


Sanity Check: Explore data on a specific Language in a State
```{r}
#Explore Spanish in California
test <- lang_app_data %>% filter(household_language == "Spanish" & state == "California")
```


Round to two decimal places
```{r}
#Round percentages to two decimal places
lang_app_data <- lang_app_data %>% mutate(across(where(is.numeric), ~ round(., digits = 2)))
```

```{r}
#Create CSV of dataframe 
#write.csv(lang_app_data,
          #"lang_app_data.csv", row.names=FALSE)
```












